name: Docker stuff
# uses https://github.com/docker/build-push-action

on:
  release:
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get the current tag name
        shell: bash
        run: echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"
        id: branchStep
      - name: Docker Build and Docker Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: singlespa/import-map-deployer:${{ steps.branchStep.outputs.tag }},singlespa/import-map-deployer:latest
